### ISSUE TITLE
Wrong cookie can be used when deploying from Docker container (?)

### ISSUE THREAD

**Issue by IsaacSchemm** [Deer-Spangle-org/faexport-old#9]
I deployed the faexport Docker container to Azure last night, and the first time I tried the "submissions" endpoint, it returned your submissions inbox instead. Tried again today, though, and it's working as expected (showing my inbox, or throwing an error if I don't provide the cookie). Any idea why this might have happened? I don't know how to reproduce it.

**Comment by Deer-Spangle** [comment]
That is... very not good! Whoopsie. I've invalidated that cookie of mine now, so at least there's that. Just trying to get faexport.spangle.org.uk back up and running.

Looks like I built my settings.yml into the docker image, that was foolish! I had best make sure that doesn't happen again

**Comment by IsaacSchemm** [comment]
Figured it was something like that! Once you have a new Docker image I'll try again. It's just me using my app, so I could just use your server, but I think it's cool to have everything deployed to one place :) Thanks for your work maintaining this - saved me from having to write scraping code.

**Comment by Deer-Spangle** [comment]
Yeah, that's embarassing! I'm really annoyed I missed that. Thanks tonnes for noticing that and telling me!

Still seems a little odd that you were able to access the submissions endpoint without a cookie, that will need more investigation. I've been eager to refactor this whole thing since February, but it has been quite an odd year!

It's updated on `version-2020.05.2` and `latest` on docker hub now, thanks again!

**Comment by Deer-Spangle** [comment]
And yeah, seems a shame how often FA scraping code has been written! I am hoping this project will reduce the instances of it, and that the automated tests can flag up as soon as they change their web design
